django-reqs/urls.py
from django.contrib import admin
from django.urls import path,include
from markdownx import urls as markdownx
from jet import urls as jet
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('', include('reqs.urls')),
    path('admin/', admin.site.urls),
    path('markdownx/', include(markdownx)),
    path('jet/', include('jet.urls', 'jet')),  # Django JET URLS
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLS
    
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

reqs/urls.py
from django.urls import path,include
from django.views.generic import TemplateView
from . import views

app_name='reqs'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('reqs/<int:pk>/',views.PdfView.as_view(),name='pdf'),
    path('about/',TemplateView.as_view(template_name='reqs/about.html'),name='about'),
    path('signup/', views.signup, name='signup'),
    path('logout/',views.reqs_logout),
]

reqs/models.py
from django.db import models
from django.utils import timezone
import datetime
from markdownx.models import MarkdownxField
from markdownx.utils import markdownify
from django.template.defaultfilters import escape

# Create your models here.
class Project(models.Model):
    project_name=models.CharField(max_length=512)
    creation_date=models.DateTimeField('date created')
    
    def __str__(self):
        return self.project_name
    
    def was_created_recently(self):
        now=timezone.now()
        return now - datetime.timedelta(days=1) <= self.creation_date <= now
    was_created_recently.admin_order_field = 'creation_date'
    was_created_recently.boolean = True
    was_created_recently.short_description = 'Created recently?'


class File(models.Model):
    project=models.ForeignKey(Project,on_delete=models.CASCADE)
    file_name=models.CharField(max_length=512,default="NewFile")
    creation_date=models.DateTimeField('date created')
    content=MarkdownxField(default="")
    def __str__(self):
        return self.file_name

    @property
    def formatted_markdown(self):
        return markdownify(self.content)

reqs/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )

reqs/views.py
from django.shortcuts import render, get_object_or_404,redirect

from django.template import loader
from django.urls import reverse
from django.views import generic
from django.views.generic import View
from django.utils import timezone
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.forms import UserCreationForm
from django.http import HttpResponse
from .render import Render
from .forms import SignUpForm
from .models import Project,File

class IndexView(generic.ListView):
    template_name='reqs/index.html'
    context_object_name='project_list'
    def get_queryset(self):
        return Project.objects.filter(creation_date__lte=timezone.now()).order_by('-creation_date')



class PdfView(View):
    
    def get(self,request, pk):
        selected_file=get_object_or_404(File,pk=pk)
        return Render.render(selected_file.formatted_markdown,
                            selected_file.file_name
                            )
        
    
   
def signup(request):
    if request.method=='POST':
        form=SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username=form.cleaned_data.get('username')
            raw_password=form.cleaned_data.get('password1')
            user=authenticate(username=username,password=raw_password)
            login(request,user)
            return redirect('../')
    else:
        form=SignUpForm()
    return render(request,'reqs/signup.html',{'form':form})


def reqs_logout(request):
    logout(request)
    return redirect('../')

reqs/templates/reqs/about.html
{% extends 'reqs/base.html' %}
{% load static %}
{% load bootstrap4 %}


{% block content %}

<p> My About Page</p>

{% endblock %}

reqs/templates/reqs/base.html
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/jstree/3.3.5/themes/default/style.min.css" />
{% extends 'reqs/bootstrap.html' %}
{% load bootstrap4 %}


{% block bootstrap4_content %}
    <div class="container">
        <h1>{% block title %}Reqs{% endblock %}</h1>

        <p>
            <a href="/">Home</a>
            {% if user.is_authenticated %}
                <a href="/logout">Logout</a>   
            {% else %}
                <a href="/admin/login/">Login</a>
                <a href="/signup">Signup</a>
            {% endif %}  
            <a href="/about">About</a>
        </p>

        {% autoescape off %}{% bootstrap_messages %}{% endautoescape %}

        {% block content %}(no content){% endblock %}
    </div>

{% endblock %}

reqs/templates/reqs/bootstrap.html
{% extends 'bootstrap4/bootstrap4.html' %}
{% block bootstrap4_title %}{% block title %}{% endblock %}{% endblock %}


{% comment %} {% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'reqs/style.css' %}" /> {% endcomment %}

reqs/templates/reqs/index.html
{% extends 'reqs/base.html' %}
{% load static %}
{% load bootstrap4 %}


{% block content %}
{% if user.is_authenticated %}
    User: {{ user.get_username }}
{% endif %}


<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jstree/3.3.5/jstree.min.js"></script>
{% if user.is_authenticated %}
    <div class="row">
        <div class="col-sm-4">
            <div id="project-container">
                {% if project_list %}
                    <ul>
                        {% for project in project_list %}
                            <li>{{ project.project_name }}
                            <ul>
                                {% for file in project.file_set.all %}
                                    <li id="{{ file.id }}" data-jstree="{{ file.formatted_markdown }}">{{ file.file_name }}</li>
                                {% endfor %}
                            </ul>
                            </li>
                        {% endfor %}
                    </ul>
                {% else %}
                <p>No projects available</p>
                {% endif %}  
                </div>
        </div>
        <div class="col-sm-8">
            <div id="project-detail" ></div>
        </div>
    </div>
{% else %}    
    <p>Reqs</p>

{% endif %}

<script>
    
    
    function show_content(content){

        $('#project-detail').html(content);
    }

    function show_content_download(file_id,filename,content){
        
        
            
        var html_link='<a href="/reqs/'+file_id+'/">'+filename+'</a></br>'+content
        $('#project-detail').html(html_link);

        
            
       
        
    }


    $(function() {
        var selectedNode = $('#project-container').jstree().bind
        ("select_node.jstree", 
            function (event, data) {
                show_content_download(data.node.id,data.node.text,data.node.data.jstree);
                //show_content(data.node.data.jstree)
            }
        )
    }); 
    


</script>





{% endblock %}

reqs/templates/reqs/links.html
<a href="/">Home</a>
 
{% if user.is_authenticated %}
     <li>User: {{ user.get_username }}</li>
     <li><a href="/logout">Logout</a></li>   
   {% else %}
     <li><a href="/admin/login/">Login</a></li>   
     <li><a href="/signup">Signup</a></li>
   {% endif %}  
<a href="/about">About</a>

reqs/templates/reqs/signup.html
{% block content %}
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
          <small style="color: grey">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
    <button type="submit">Sign up</button>
  </form>
{% endblock %}